# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

footlocker = Store.create(name: "Footlocker", city: "Tysons")
kith = Store.create(name: "Kith", city: "New York City")
flight_club = Store.create(name: "Flight Club", city: "New York City")
ubiq = Store.create(name: "Ubiq", city: "Philadelphia")
dtlr = Store.create(name: "DTLR", city: "Columbia")
undefeated = Store.create(name: "Undefeated", city: "Los Angeles")


adidas = Brand.create(name: "Adidas")
nike = Brand.create(name: "Nike")
jordan = Brand.create(name: "Jordan")
under_armour = Brand.create(name: "Under Armour")
converse = Brand.create(name: "Converse")
vans = Brand.create(name: "Vans")

richard = User.create(name: "Richard", username: "richeekim", password: "password")
deep = User.create(name: "Deep", username: "Deepanator", password: "password")


# yeezy_350 = Shoe.create(name: "Yeezy 350 Boost", tech: "Boost", price: 3000, brand_id: 1)
# pharrel_nmd = Shoe.create(name: "Pharrel F&F NMD", tech: "Boost", price: 10000, brand_id: 1)
# jordan_1 = Shoe.create(name: "Jordan 1", tech: "Air", price: 160, brand_id: 3)
# foamposite = Shoe.create(name: "Foamposite", tech: "Zoom Air", price: 230, brand_id: 2)
# chuck_taylor = Shoe.create(name: "Chuck Taylor", tech: "Lunarlon", price: 50, brand_id: 5)
# curry_4 = Shoe.create(name: "Curry 4", tech: "Charged Foam", price: 130, brand_id: 4)
# old_skool = Shoe.create(name: "Old Skool", tech: "Ultracush", price: 60, brand_id: 6)
# air_mag = Shoe.create(name: "Air Mag", tech: "Self-lacing", price: 40800, brand_id: 1)



yeezy_350_7 = Shoe.create(name: "Yeezy 350 Boost - Size 7", size: 7, tech: "Boost", price: 2500, brand_id: 1)
yeezy_350_8 = Shoe.create(name: "Yeezy 350 Boost - Size 8", size: 8, tech: "Boost", price: 3000, brand_id: 1)
yeezy_350_9 = Shoe.create(name: "Yeezy 350 Boost - Size 9", size: 9, tech: "Boost", price: 2600, brand_id: 1)
yeezy_350_10 = Shoe.create(name: "Yeezy 350 Boost - Size 10", size: 10, tech: "Boost", price: 2100, brand_id: 1)
yeezy_350_11 = Shoe.create(name: "Yeezy 350 Boost - Size 11", size: 11, tech: "Boost", price: 2250, brand_id: 1)
pharrel_nmd_7 = Shoe.create(name: "Pharrel F&F NMD - Size 7", size: 7, tech: "Boost", price: 10000, brand_id: 1)
pharrel_nmd_9 = Shoe.create(name: "Pharrel F&F NMD - Size 9", size: 9, tech: "Boost", price: 9000, brand_id: 1)
pharrel_nmd_12 = Shoe.create(name: "Pharrel F&F NMD - Size 12", size: 12, tech: "Boost", price: 12000, brand_id: 1)
jordan_1_7 = Shoe.create(name: "Jordan 1 - Size 7", size: 7, tech: "Air", price: 160, brand_id: 3)
jordan_1_8 = Shoe.create(name: "Jordan 1 - Size 8", size: 8, tech: "Air", price: 160, brand_id: 3)
jordan_1_9 = Shoe.create(name: "Jordan 1 - Size 9", size: 9, tech: "Air", price: 160, brand_id: 3)
jordan_1_10 = Shoe.create(name: "Jordan 1 - Size 10", size: 10, tech: "Air", price: 160, brand_id: 3)
jordan_1_11 = Shoe.create(name: "Jordan 1 - Size 11", size: 11, tech: "Air", price: 160, brand_id: 3)
jordan_1_12 = Shoe.create(name: "Jordan 1 - Size 12", size: 12, tech: "Air", price: 160, brand_id: 3)
foamposite_7 = Shoe.create(name: "Foamposite - Size 7", size: 7, tech: "Zoom Air", price: 230, brand_id: 2)
foamposite_8 = Shoe.create(name: "Foamposite - Size 8", size: 8, tech: "Zoom Air", price: 230, brand_id: 2)
foamposite_9 = Shoe.create(name: "Foamposite - Size 9", size: 9, tech: "Zoom Air", price: 230, brand_id: 2)
foamposite_10 = Shoe.create(name: "Foamposite - Size 10", size: 10, tech: "Zoom Air", price: 230, brand_id: 2)
foamposite_11 = Shoe.create(name: "Foamposite - Size 11", size: 11, tech: "Zoom Air", price: 230, brand_id: 2)
foamposite_12 = Shoe.create(name: "Foamposite - Size 12", size: 12, tech: "Zoom Air", price: 230, brand_id: 2)
chuck_taylor_5 = Shoe.create(name: "Chuck Taylor - Size 5", size: 5, tech: "Lunarlon", price: 50, brand_id: 5)
chuck_taylor_6 = Shoe.create(name: "Chuck Taylor - Size 6", size: 6, tech: "Lunarlon", price: 50, brand_id: 5)
chuck_taylor_7 = Shoe.create(name: "Chuck Taylor - Size 7", size: 7, tech: "Lunarlon", price: 50, brand_id: 5)
chuck_taylor_8 = Shoe.create(name: "Chuck Taylor - Size 8", size: 8, tech: "Lunarlon", price: 50, brand_id: 5)
chuck_taylor_9 = Shoe.create(name: "Chuck Taylor - Size 9", size: 9, tech: "Lunarlon", price: 50, brand_id: 5)
chuck_taylor_10 = Shoe.create(name: "Chuck Taylor - Size 10", size: 10, tech: "Lunarlon", price: 50, brand_id: 5)
chuck_taylor_11 = Shoe.create(name: "Chuck Taylor - Size 11", size: 11, tech: "Lunarlon", price: 50, brand_id: 5)
chuck_taylor_12 = Shoe.create(name: "Chuck Taylor - Size 12", size: 12, tech: "Lunarlon", price: 50, brand_id: 5)
chuck_taylor_13 = Shoe.create(name: "Chuck Taylor - Size 13", size: 13, tech: "Lunarlon", price: 50, brand_id: 5)
curry_4_7 = Shoe.create(name: "Curry 4 - Size 7", size: 7, tech: "Charged Foam", price: 130, brand_id: 4)
curry_4_8 = Shoe.create(name: "Curry 4 - Size 8", size: 8, tech: "Charged Foam", price: 130, brand_id: 4)
curry_4_9 = Shoe.create(name: "Curry 4 - Size 9", size: 9, tech: "Charged Foam", price: 130, brand_id: 4)
curry_4_10 = Shoe.create(name: "Curry 4 - Size 10", size: 10, tech: "Charged Foam", price: 130, brand_id: 4)
curry_4_11 = Shoe.create(name: "Curry 4 - Size 11", size: 11, tech: "Charged Foam", price: 130, brand_id: 4)
curry_4_12 = Shoe.create(name: "Curry 4 - Size 12", size: 12, tech: "Charged Foam", price: 130, brand_id: 4)
old_skool_6 = Shoe.create(name: "Old Skool - Size 6", size: 6, tech: "Ultracush", price: 60, brand_id: 6)
old_skool_7 = Shoe.create(name: "Old Skool - Size 7", size: 7, tech: "Ultracush", price: 60, brand_id: 6)
old_skool_8 = Shoe.create(name: "Old Skool - Size 8", size: 8, tech: "Ultracush", price: 60, brand_id: 6)
old_skool_9 = Shoe.create(name: "Old Skool - Size 9", size: 9, tech: "Ultracush", price: 60, brand_id: 6)
old_skool_10 = Shoe.create(name: "Old Skool - Size 10", size: 10, tech: "Ultracush", price: 60, brand_id: 6)
old_skool_11 = Shoe.create(name: "Old Skool - Size 11", size: 11, tech: "Ultracush", price: 60, brand_id: 6)
old_skool_12 = Shoe.create(name: "Old Skool - Size 12", size: 12, tech: "Ultracush", price: 60, brand_id: 6)
air_mag_11 = Shoe.create(name: "Air Mag - Size 11", size: 11, tech: "Self-lacing", price: 40800, brand_id: 1)


yeezy1 = ShoeStore.create(quantity: 1, store_id: 3, shoe_id: 1)
yeezy2 = ShoeStore.create(quantity: 1, store_id: 3, shoe_id: 2)
yeezy3 = ShoeStore.create(quantity: 1, store_id: 3, shoe_id: 3)
yeezy4 = ShoeStore.create(quantity: 1, store_id: 3, shoe_id: 4)
yeezy5 = ShoeStore.create(quantity: 1, store_id: 3, shoe_id: 5)

nmd1 = ShoeStore.create(quantity: 1, store_id: 3, shoe_id: 6)
nmd2 = ShoeStore.create(quantity: 1, store_id: 3, shoe_id: 7)
nmd3 = ShoeStore.create(quantity: 1, store_id: 3, shoe_id: 8)

jordan1 = ShoeStore.create(quantity: 15, store_id: 1, shoe_id: 9)
jordan2 = ShoeStore.create(quantity: 13, store_id: 1, shoe_id: 10)
jordan3 = ShoeStore.create(quantity: 20, store_id: 1, shoe_id: 11)
jordan4 = ShoeStore.create(quantity: 11, store_id: 1, shoe_id: 12)
jordan5 = ShoeStore.create(quantity: 30, store_id: 1, shoe_id: 13)
jordan6 = ShoeStore.create(quantity: 10, store_id: 1, shoe_id: 14)

jordan7 = ShoeStore.create(quantity: 9, store_id: 2, shoe_id: 9)
jordan8 = ShoeStore.create(quantity: 14, store_id: 2, shoe_id: 10)
jordan9 = ShoeStore.create(quantity: 19, store_id: 2, shoe_id: 11)
jordan10 = ShoeStore.create(quantity: 9, store_id: 2, shoe_id: 12)
jordan11 = ShoeStore.create(quantity: 20, store_id: 2, shoe_id: 13)
jordan12 = ShoeStore.create(quantity: 17, store_id: 2, shoe_id: 14)

jordan13 = ShoeStore.create(quantity: 19, store_id: 4, shoe_id: 9)
jordan14 = ShoeStore.create(quantity: 17, store_id: 4, shoe_id: 10)
jordan15 = ShoeStore.create(quantity: 34, store_id: 4, shoe_id: 11)
jordan16 = ShoeStore.create(quantity: 13, store_id: 4, shoe_id: 12)
jordan17 = ShoeStore.create(quantity: 23, store_id: 4, shoe_id: 13)
jordan18 = ShoeStore.create(quantity: 10, store_id: 4, shoe_id: 14)

jordan19 = ShoeStore.create(quantity: 15, store_id: 5, shoe_id: 9)
jordan20 = ShoeStore.create(quantity: 23, store_id: 5, shoe_id: 10)
jordan21 = ShoeStore.create(quantity: 20, store_id: 5, shoe_id: 11)
jordan22 = ShoeStore.create(quantity: 31, store_id: 5, shoe_id: 12)
jordan23 = ShoeStore.create(quantity: 40, store_id: 5, shoe_id: 13)
jordan24 = ShoeStore.create(quantity: 10, store_id: 5, shoe_id: 14)

foam1 = ShoeStore.create(quantity: 10, store_id: 5, shoe_id: 15)
foam2 = ShoeStore.create(quantity: 9, store_id: 5, shoe_id: 16)
foam3 = ShoeStore.create(quantity: 13, store_id: 5, shoe_id: 17)
foam4 = ShoeStore.create(quantity: 12, store_id: 5, shoe_id: 18)
foam5 = ShoeStore.create(quantity: 7, store_id: 5, shoe_id: 19)
foam6 = ShoeStore.create(quantity: 11, store_id: 5, shoe_id: 20)

foam7 = ShoeStore.create(quantity: 5, store_id: 1, shoe_id: 15)
foam8 = ShoeStore.create(quantity: 13, store_id: 1, shoe_id: 16)
foam9 = ShoeStore.create(quantity: 20, store_id: 1, shoe_id: 17)
foam10 = ShoeStore.create(quantity: 15, store_id: 1, shoe_id: 18)
foam11 = ShoeStore.create(quantity: 2, store_id: 1, shoe_id: 19)
foam12 = ShoeStore.create(quantity: 4, store_id: 1, shoe_id: 20)

chuck1 = ShoeStore.create(quantity: 30, store_id: 1, shoe_id: 21)
chuck2 = ShoeStore.create(quantity: 30, store_id: 1, shoe_id: 22)
chuck3 = ShoeStore.create(quantity: 30, store_id: 1, shoe_id: 23)
chuck4 = ShoeStore.create(quantity: 30, store_id: 1, shoe_id: 24)
chuck5 = ShoeStore.create(quantity: 30, store_id: 1, shoe_id: 25)
chuck6 = ShoeStore.create(quantity: 30, store_id: 1, shoe_id: 26)
chuck7 = ShoeStore.create(quantity: 30, store_id: 1, shoe_id: 27)
chuck8 = ShoeStore.create(quantity: 30, store_id: 1, shoe_id: 28)
chuck9 = ShoeStore.create(quantity: 30, store_id: 1, shoe_id: 29)

chuck10 = ShoeStore.create(quantity: 20, store_id: 2, shoe_id: 21)
chuck11 = ShoeStore.create(quantity: 20, store_id: 2, shoe_id: 22)
chuck12 = ShoeStore.create(quantity: 20, store_id: 2, shoe_id: 23)
chuck13 = ShoeStore.create(quantity: 20, store_id: 2, shoe_id: 24)
chuck14 = ShoeStore.create(quantity: 20, store_id: 2, shoe_id: 25)
chuck15 = ShoeStore.create(quantity: 20, store_id: 2, shoe_id: 26)
chuck16 = ShoeStore.create(quantity: 20, store_id: 2, shoe_id: 27)
chuck17 = ShoeStore.create(quantity: 20, store_id: 2, shoe_id: 28)
chuck18 = ShoeStore.create(quantity: 20, store_id: 2, shoe_id: 29)

chuck19 = ShoeStore.create(quantity: 35, store_id: 3, shoe_id: 21)
chuck20 = ShoeStore.create(quantity: 35, store_id: 3, shoe_id: 22)
chuck21 = ShoeStore.create(quantity: 35, store_id: 3, shoe_id: 23)
chuck22 = ShoeStore.create(quantity: 35, store_id: 3, shoe_id: 24)
chuck23 = ShoeStore.create(quantity: 35, store_id: 3, shoe_id: 25)
chuck24 = ShoeStore.create(quantity: 35, store_id: 3, shoe_id: 26)
chuck25 = ShoeStore.create(quantity: 35, store_id: 3, shoe_id: 27)
chuck26 = ShoeStore.create(quantity: 35, store_id: 3, shoe_id: 28)
chuck27 = ShoeStore.create(quantity: 35, store_id: 3, shoe_id: 29)

chuck28 = ShoeStore.create(quantity: 10, store_id: 4, shoe_id: 21)
chuck29 = ShoeStore.create(quantity: 10, store_id: 4, shoe_id: 22)
chuck30 = ShoeStore.create(quantity: 10, store_id: 4, shoe_id: 23)
chuck31 = ShoeStore.create(quantity: 10, store_id: 4, shoe_id: 24)
chuck32 = ShoeStore.create(quantity: 10, store_id: 4, shoe_id: 25)
chuck33 = ShoeStore.create(quantity: 10, store_id: 4, shoe_id: 26)
chuck34 = ShoeStore.create(quantity: 10, store_id: 4, shoe_id: 27)
chuck35 = ShoeStore.create(quantity: 10, store_id: 4, shoe_id: 28)
chuck36 = ShoeStore.create(quantity: 10, store_id: 4, shoe_id: 29)

chuck37 = ShoeStore.create(quantity: 30, store_id: 5, shoe_id: 21)
chuck38 = ShoeStore.create(quantity: 30, store_id: 5, shoe_id: 22)
chuck39 = ShoeStore.create(quantity: 30, store_id: 5, shoe_id: 23)
chuck40 = ShoeStore.create(quantity: 30, store_id: 5, shoe_id: 24)
chuck41 = ShoeStore.create(quantity: 30, store_id: 5, shoe_id: 25)
chuck42 = ShoeStore.create(quantity: 30, store_id: 5, shoe_id: 26)
chuck43 = ShoeStore.create(quantity: 30, store_id: 5, shoe_id: 27)
chuck44 = ShoeStore.create(quantity: 30, store_id: 5, shoe_id: 28)
chuck45 = ShoeStore.create(quantity: 30, store_id: 5, shoe_id: 29)

chuck46 = ShoeStore.create(quantity: 23, store_id: 6, shoe_id: 21)
chuck47 = ShoeStore.create(quantity: 23, store_id: 6, shoe_id: 22)
chuck48 = ShoeStore.create(quantity: 23, store_id: 6, shoe_id: 23)
chuck49 = ShoeStore.create(quantity: 23, store_id: 6, shoe_id: 24)
chuck50 = ShoeStore.create(quantity: 23, store_id: 6, shoe_id: 25)
chuck51 = ShoeStore.create(quantity: 23, store_id: 6, shoe_id: 26)
chuck52 = ShoeStore.create(quantity: 23, store_id: 6, shoe_id: 27)
chuck53 = ShoeStore.create(quantity: 23, store_id: 6, shoe_id: 28)
chuck54 = ShoeStore.create(quantity: 23, store_id: 6, shoe_id: 29)

curry1 = ShoeStore.create(quantity: 13, store_id: 1, shoe_id: 30)
curry2 = ShoeStore.create(quantity: 13, store_id: 1, shoe_id: 31)
curry3 = ShoeStore.create(quantity: 13, store_id: 1, shoe_id: 32)
curry4 = ShoeStore.create(quantity: 13, store_id: 1, shoe_id: 33)
curry5 = ShoeStore.create(quantity: 13, store_id: 1, shoe_id: 34)
curry6 = ShoeStore.create(quantity: 13, store_id: 1, shoe_id: 35)

curry7 = ShoeStore.create(quantity: 13, store_id: 5, shoe_id: 30)
curry8 = ShoeStore.create(quantity: 13, store_id: 5, shoe_id: 31)
curry9 = ShoeStore.create(quantity: 13, store_id: 5, shoe_id: 32)
curry10 = ShoeStore.create(quantity: 13, store_id: 5, shoe_id: 33)
curry11 = ShoeStore.create(quantity: 13, store_id: 5, shoe_id: 34)
curry12 = ShoeStore.create(quantity: 13, store_id: 5, shoe_id: 35)

oldskool1 = ShoeStore.create(quantity: 18, store_id: 1, shoe_id: 36)
oldskool2 = ShoeStore.create(quantity: 12, store_id: 1, shoe_id: 37)
oldskool3 = ShoeStore.create(quantity: 1, store_id: 1, shoe_id: 38)
oldskool4 = ShoeStore.create(quantity: 17, store_id: 1, shoe_id: 39)
oldskool5 = ShoeStore.create(quantity: 20, store_id: 1, shoe_id: 40)
oldskool6 = ShoeStore.create(quantity: 21, store_id: 1, shoe_id: 41)
oldskool7 = ShoeStore.create(quantity: 8, store_id: 1, shoe_id: 42)

oldskool8 = ShoeStore.create(quantity: 13, store_id: 2, shoe_id: 36)
oldskool9 = ShoeStore.create(quantity: 12, store_id: 2, shoe_id: 37)
oldskool10 = ShoeStore.create(quantity: 13, store_id: 2, shoe_id: 38)
oldskool11 = ShoeStore.create(quantity: 14, store_id: 2, shoe_id: 39)
oldskool12 = ShoeStore.create(quantity: 34, store_id: 2, shoe_id: 40)
oldskool13 = ShoeStore.create(quantity: 21, store_id: 2, shoe_id: 41)
oldskool14 = ShoeStore.create(quantity: 8, store_id: 2, shoe_id: 42)

oldskool15 = ShoeStore.create(quantity: 24, store_id: 4, shoe_id: 36)
oldskool16 = ShoeStore.create(quantity: 23, store_id: 4, shoe_id: 37)
oldskool17 = ShoeStore.create(quantity: 13, store_id: 4, shoe_id: 38)
oldskool18 = ShoeStore.create(quantity: 17, store_id: 4, shoe_id: 39)
oldskool19 = ShoeStore.create(quantity: 28, store_id: 4, shoe_id: 40)
oldskool20 = ShoeStore.create(quantity: 21, store_id: 4, shoe_id: 41)
oldskool21 = ShoeStore.create(quantity: 3, store_id: 4, shoe_id: 42)

air_mag1 = ShoeStore.create(quantity: 1, store_id: 3, shoe_id: 43)

#USERSHOES
yeezys1 = UserShoe.create(user_id: 1, shoe_id: 1)
yeezys2 = UserShoe.create(user_id: 1, shoe_id: 2)
yeezys3 = UserShoe.create(user_id: 1, shoe_id: 3)
yeezys4 = UserShoe.create(user_id: 1, shoe_id: 4)
yeezys5 = UserShoe.create(user_id: 1, shoe_id: 5)

nmds1 = UserShoe.create(user_id: 1, shoe_id: 6)
nmds2 = UserShoe.create(user_id: 1, shoe_id: 7)
nmds3 = UserShoe.create(user_id: 1, shoe_id: 8)

jordans1 = UserShoe.create(user_id: 1, shoe_id: 9)
jordans2 = UserShoe.create(user_id: 1, shoe_id: 10)
jordans3 = UserShoe.create(user_id: 1, shoe_id: 11)
jordans4 = UserShoe.create(user_id: 1, shoe_id: 12)
jordans5 = UserShoe.create(user_id: 1, shoe_id: 13)
jordans6 = UserShoe.create(user_id: 1, shoe_id: 14)

jordans7 = UserShoe.create(user_id: 2, shoe_id: 9)
jordans8 = UserShoe.create(user_id: 2, shoe_id: 10)
jordans9 = UserShoe.create(user_id: 2, shoe_id: 11)
jordans10 = UserShoe.create(user_id: 2, shoe_id: 12)
jordans11 = UserShoe.create(user_id: 2, shoe_id: 13)
jordans12 = UserShoe.create(user_id: 2, shoe_id: 14)

jordans13 = UserShoe.create(user_id: 2, shoe_id: 9)
jordans14 = UserShoe.create(user_id: 1, shoe_id: 10)
jordans15 = UserShoe.create(user_id: 1, shoe_id: 11)
jordans16 = UserShoe.create(user_id: 1, shoe_id: 12)
jordans17 = UserShoe.create(user_id: 1, shoe_id: 13)
jordans18 = UserShoe.create(user_id: 2, shoe_id: 14)

jordans19 = UserShoe.create(user_id: 2, shoe_id: 9)
jordans20 = UserShoe.create(user_id: 1, shoe_id: 10)
jordans21 = UserShoe.create(user_id: 1, shoe_id: 11)
jordans22 = UserShoe.create(user_id: 1, shoe_id: 12)
jordans23 = UserShoe.create(user_id: 1, shoe_id: 13)
jordans24 = UserShoe.create(user_id: 1, shoe_id: 14)

foams1 = UserShoe.create(user_id: 2, shoe_id: 15)
foams2 = UserShoe.create(user_id: 2, shoe_id: 16)
foams3 = UserShoe.create(user_id: 2, shoe_id: 17)
foams4 = UserShoe.create(user_id: 2, shoe_id: 18)
foams5 = UserShoe.create(user_id: 2, shoe_id: 19)
foams6 = UserShoe.create(user_id: 2, shoe_id: 20)

foams7 = UserShoe.create(user_id: 1, shoe_id: 15)
foams8 = UserShoe.create(user_id: 1, shoe_id: 16)
foams9 = UserShoe.create(user_id: 1, shoe_id: 17)
foams10 = UserShoe.create(user_id: 1, shoe_id: 18)
foams11 = UserShoe.create(user_id: 1, shoe_id: 19)
foams12 = UserShoe.create(user_id: 1, shoe_id: 20)

chucks1 = UserShoe.create(user_id: 1, shoe_id: 21)
chucks2 = UserShoe.create(user_id: 1, shoe_id: 22)
chucks3 = UserShoe.create(user_id: 1, shoe_id: 23)
chucks4 = UserShoe.create(user_id: 1, shoe_id: 24)
chucks5 = UserShoe.create(user_id: 1, shoe_id: 25)
chucks6 = UserShoe.create(user_id: 1, shoe_id: 26)
chucks7 = UserShoe.create(user_id: 1, shoe_id: 27)
chucks8 = UserShoe.create(user_id: 1, shoe_id: 28)
chucks9 = UserShoe.create(user_id: 1, shoe_id: 29)

chucks10 = UserShoe.create(user_id: 2, shoe_id: 21)
chucks11 = UserShoe.create(user_id: 2, shoe_id: 22)
chucks12 = UserShoe.create(user_id: 2, shoe_id: 23)
chucks13 = UserShoe.create(user_id: 2, shoe_id: 24)
chucks14 = UserShoe.create(user_id: 2, shoe_id: 25)
chucks15 = UserShoe.create(user_id: 2, shoe_id: 26)
chucks16 = UserShoe.create(user_id: 2, shoe_id: 27)
chucks17 = UserShoe.create(user_id: 2, shoe_id: 28)
chucks18 = UserShoe.create(user_id: 2, shoe_id: 29)

chucks19 = UserShoe.create(user_id: 2, shoe_id: 21)
chucks20 = UserShoe.create(user_id: 2, shoe_id: 22)
chucks21 = UserShoe.create(user_id: 2, shoe_id: 23)
chucks22 = UserShoe.create(user_id: 2, shoe_id: 24)
chucks23 = UserShoe.create(user_id: 2, shoe_id: 25)
chucks24 = UserShoe.create(user_id: 2, shoe_id: 26)
chucks25 = UserShoe.create(user_id: 2, shoe_id: 27)
chucks26 = UserShoe.create(user_id: 2, shoe_id: 28)
chucks27 = UserShoe.create(user_id: 2, shoe_id: 29)

chucks28 = UserShoe.create(user_id: 2, shoe_id: 21)
chucks29 = UserShoe.create(user_id: 2, shoe_id: 22)
chucks30 = UserShoe.create(user_id: 2, shoe_id: 23)
chucks31 = UserShoe.create(user_id: 2, shoe_id: 24)
chucks32 = UserShoe.create(user_id: 2, shoe_id: 25)
chucks33 = UserShoe.create(user_id: 2, shoe_id: 26)
chucks34 = UserShoe.create(user_id: 2, shoe_id: 27)
chucks35 = UserShoe.create(user_id: 2, shoe_id: 28)
chucks36 = UserShoe.create(user_id: 2, shoe_id: 29)

chucks37 = UserShoe.create(user_id: 2, shoe_id: 21)
chucks38 = UserShoe.create(user_id: 2, shoe_id: 22)
chucks39 = UserShoe.create(user_id: 2, shoe_id: 23)
chucks40 = UserShoe.create(user_id: 2, shoe_id: 24)
chucks41 = UserShoe.create(user_id: 2, shoe_id: 25)
chucks42 = UserShoe.create(user_id: 2, shoe_id: 26)
chucks43 = UserShoe.create(user_id: 2, shoe_id: 27)
chucks44 = UserShoe.create(user_id: 2, shoe_id: 28)
chucks45 = UserShoe.create(user_id: 2, shoe_id: 29)

chucks46 = UserShoe.create(user_id: 2, shoe_id: 21)
chucks47 = UserShoe.create(user_id: 2, shoe_id: 22)
chucks48 = UserShoe.create(user_id: 2, shoe_id: 23)
chucks49 = UserShoe.create(user_id: 2, shoe_id: 24)
chucks50 = UserShoe.create(user_id: 2, shoe_id: 25)
chucks51 = UserShoe.create(user_id: 2, shoe_id: 26)
chucks52 = UserShoe.create(user_id: 2, shoe_id: 27)
chucks53 = UserShoe.create(user_id: 2, shoe_id: 28)
chucks54 = UserShoe.create(user_id: 2, shoe_id: 29)

currys1 = UserShoe.create(user_id: 1, shoe_id: 30)
currys2 = UserShoe.create(user_id: 1, shoe_id: 31)
currys3 = UserShoe.create(user_id: 1, shoe_id: 32)
currys4 = UserShoe.create(user_id: 1, shoe_id: 33)
currys5 = UserShoe.create(user_id: 1, shoe_id: 34)
currys6 = UserShoe.create(user_id: 1, shoe_id: 35)

currys7 = UserShoe.create(user_id: 2, shoe_id: 30)
currys8 = UserShoe.create(user_id: 2, shoe_id: 31)
currys9 = UserShoe.create(user_id: 2, shoe_id: 32)
currys10 = UserShoe.create(user_id: 2, shoe_id: 33)
currys11 = UserShoe.create(user_id: 2, shoe_id: 34)
currys12 = UserShoe.create(user_id: 2, shoe_id: 35)

oldskools1 = UserShoe.create(user_id: 1, shoe_id: 36)
oldskools2 = UserShoe.create(user_id: 1, shoe_id: 37)
oldskools3 = UserShoe.create(user_id: 1, shoe_id: 38)
oldskools4 = UserShoe.create(user_id: 1, shoe_id: 39)
oldskools5 = UserShoe.create(user_id: 1, shoe_id: 40)
oldskools6 = UserShoe.create(user_id: 1, shoe_id: 41)
oldskools7 = UserShoe.create(user_id: 1, shoe_id: 42)

oldskools8 = UserShoe.create(user_id: 2, shoe_id: 36)
oldskools9 = UserShoe.create(user_id: 2, shoe_id: 37)
oldskools10 = UserShoe.create(user_id: 2, shoe_id: 38)
oldskools11 = UserShoe.create(user_id: 2, shoe_id: 39)
oldskools12 = UserShoe.create(user_id: 2, shoe_id: 40)
oldskools13 = UserShoe.create(user_id: 2, shoe_id: 41)
oldskools14 = UserShoe.create(user_id: 2, shoe_id: 42)

oldskools15 = UserShoe.create(user_id: 1, shoe_id: 36)
oldskools16 = UserShoe.create(user_id: 1, shoe_id: 37)
oldskools17 = UserShoe.create(user_id: 1, shoe_id: 38)
oldskools18 = UserShoe.create(user_id: 1, shoe_id: 39)
oldskools19 = UserShoe.create(user_id: 1, shoe_id: 40)
oldskools20 = UserShoe.create(user_id: 1, shoe_id: 41)
oldskools21 = UserShoe.create(user_id: 1, shoe_id: 42)

air_mags1 = UserShoe.create(user_id: 1, shoe_id: 43)
