# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

footlocker = Store.create(name: "Footlocker", city: "Tysons")
kith = Store.create(name: "Kith", city: "New York City")
flight_club = Store.create(name: "Flight Club", city: "New York City")
ubiq = Store.create(name: "Ubiq", city: "Philadelphia")
dtlr = Store.create(name: "DTLR", city: "Columbia")
undefeated = Store.create(name: "Undefeated", city: "Los Angeles")


adidas = Brand.create(name: "Adidas")
nike = Brand.create(name: "Nike")
jordan = Brand.create(name: "Jordan")
under_armour = Brand.create(name: "Under Armour")
converse = Brand.create(name: "Converse")
vans = Brand.create(name: "Vans")


yeezy_350 = Shoe.create(name: "Yeezy 350 Boost", tech: "Boost", price: 3000, brand_id: 1)
pharrel_nmd = Shoe.create(name: "Pharrel F&F NMD", tech: "Boost", price: 10000, brand_id: 1)
jordan_1 = Shoe.create(name: "Jordan 1", tech: "Air", price: 160, brand_id: 3)
foamposite = Shoe.create(name: "Foamposite", tech: "Zoom Air", price: 230, brand_id: 2)
chuck_taylor = Shoe.create(name: "Chuck Taylor", tech: "Lunarlon", price: 50, brand_id: 5)
curry_4 = Shoe.create(name: "Curry 4", tech: "Charged Foam", price: 130, brand_id: 4)
old_skool = Shoe.create(name: "Old Skool", tech: "Ultracush", price: 60, brand_id: 6)
air_mag = Shoe.create(name: "Air Mag", size: 11, tech: "Self-lacing", price: 40800, brand_id: 1)

size5 = Size.create(size: 5)
size6 = Size.create(size: 6)
size7 = Size.create(size: 7)
size8 = Size.create(size: 8)
size9 = Size.create(size: 9)
size10 = Size.create(size: 10)
size11 = Size.create(size: 11)
size12 = Size.create(size: 12)
size13 = Size.create(size: 13)






# yeezy_350_7 = Shoe.create(name: "Yeezy 350 Boost", size: 7, tech: "Boost", price: 2500, brand_id: 1)
# yeezy_350_8 = Shoe.create(name: "Yeezy 350 Boost", size: 8, tech: "Boost", price: 3000, brand_id: 1)
# yeezy_350_9 = Shoe.create(name: "Yeezy 350 Boost", size: 9, tech: "Boost", price: 2600, brand_id: 1)
# yeezy_350_10 = Shoe.create(name: "Yeezy 350 Boost", size: 10, tech: "Boost", price: 2100, brand_id: 1)
# yeezy_350_11 = Shoe.create(name: "Yeezy 350 Boost", size: 11, tech: "Boost", price: 2250, brand_id: 1)
# pharrel_nmd_7 = Shoe.create(name: "Pharrel F&F NMD", size: 7, tech: "Boost", price: 10000, brand_id: 1)
# pharrel_nmd_9 = Shoe.create(name: "Pharrel F&F NMD", size: 9, tech: "Boost", price: 9000, brand_id: 1)
# pharrel_nmd_12 = Shoe.create(name: "Pharrel F&F NMD", size: 12, tech: "Boost", price: 12000, brand_id: 1)
# jordan_1_7 = Shoe.create(name: "Jordan 1", size: 7, tech: "Air", price: 160, brand_id: 3)
# jordan_1_8 = Shoe.create(name: "Jordan 1", size: 8, tech: "Air", price: 160, brand_id: 3)
# jordan_1_9 = Shoe.create(name: "Jordan 1", size: 9, tech: "Air", price: 160, brand_id: 3)
# jordan_1_10 = Shoe.create(name: "Jordan 1", size: 10, tech: "Air", price: 160, brand_id: 3)
# jordan_1_11 = Shoe.create(name: "Jordan 1", size: 11, tech: "Air", price: 160, brand_id: 3)
# jordan_1_12 = Shoe.create(name: "Jordan 1", size: 12, tech: "Air", price: 160, brand_id: 3)
# foamposite_7 = Shoe.create(name: "Foamposite", size: 7, tech: "Zoom Air", price: 230, brand_id: 2)
# foamposite_8 = Shoe.create(name: "Foamposite", size: 8, tech: "Zoom Air", price: 230, brand_id: 2)
# foamposite_9 = Shoe.create(name: "Foamposite", size: 9, tech: "Zoom Air", price: 230, brand_id: 2)
# foamposite_10 = Shoe.create(name: "Foamposite", size: 10, tech: "Zoom Air", price: 230, brand_id: 2)
# foamposite_11 = Shoe.create(name: "Foamposite", size: 11, tech: "Zoom Air", price: 230, brand_id: 2)
# foamposite_12 = Shoe.create(name: "Foamposite", size: 12, tech: "Zoom Air", price: 230, brand_id: 2)
# chuck_taylor_5 = Shoe.create(name: "Chuck Taylor", size: 5, tech: "Lunarlon", price: 50, brand_id: 5)
# chuck_taylor_6 = Shoe.create(name: "Chuck Taylor", size: 6, tech: "Lunarlon", price: 50, brand_id: 5)
# chuck_taylor_7 = Shoe.create(name: "Chuck Taylor", size: 7, tech: "Lunarlon", price: 50, brand_id: 5)
# chuck_taylor_8 = Shoe.create(name: "Chuck Taylor", size: 8, tech: "Lunarlon", price: 50, brand_id: 5)
# chuck_taylor_9 = Shoe.create(name: "Chuck Taylor", size: 9, tech: "Lunarlon", price: 50, brand_id: 5)
# chuck_taylor_10 = Shoe.create(name: "Chuck Taylor", size: 10, tech: "Lunarlon", price: 50, brand_id: 5)
# chuck_taylor_11 = Shoe.create(name: "Chuck Taylor", size: 11, tech: "Lunarlon", price: 50, brand_id: 5)
# chuck_taylor_12 = Shoe.create(name: "Chuck Taylor", size: 12, tech: "Lunarlon", price: 50, brand_id: 5)
# chuck_taylor_13 = Shoe.create(name: "Chuck Taylor", size: 13, tech: "Lunarlon", price: 50, brand_id: 5)
# curry_4_7 = Shoe.create(name: "Curry 4", size: 7, tech: "Charged Foam", price: 130, brand_id: 4)
# curry_4_8 = Shoe.create(name: "Curry 4", size: 8, tech: "Charged Foam", price: 130, brand_id: 4)
# curry_4_9 = Shoe.create(name: "Curry 4", size: 9, tech: "Charged Foam", price: 130, brand_id: 4)
# curry_4_10 = Shoe.create(name: "Curry 4", size: 10, tech: "Charged Foam", price: 130, brand_id: 4)
# curry_4_11 = Shoe.create(name: "Curry 4", size: 11, tech: "Charged Foam", price: 130, brand_id: 4)
# curry_4_12 = Shoe.create(name: "Curry 4", size: 12, tech: "Charged Foam", price: 130, brand_id: 4)
# old_skool_6 = Shoe.create(name: "Old Skool", size: 6, tech: "Ultracush", price: 60, brand_id: 6)
# old_skool_7 = Shoe.create(name: "Old Skool", size: 7, tech: "Ultracush", price: 60, brand_id: 6)
# old_skool_8 = Shoe.create(name: "Old Skool", size: 8, tech: "Ultracush", price: 60, brand_id: 6)
# old_skool_9 = Shoe.create(name: "Old Skool", size: 9, tech: "Ultracush", price: 60, brand_id: 6)
# old_skool_10 = Shoe.create(name: "Old Skool", size: 10, tech: "Ultracush", price: 60, brand_id: 6)
# old_skool_11 = Shoe.create(name: "Old Skool", size: 11, tech: "Ultracush", price: 60, brand_id: 6)
# old_skool_12 = Shoe.create(name: "Old Skool", size: 12, tech: "Ultracush", price: 60, brand_id: 6)
# air_mag_11 = Shoe.create(name: "Air Mag", size: 11, tech: "Self-lacing", price: 40800, brand_id: 1)
#
#
# yeezy1 = ShoeStore.create(quantity: 1, store_id: 3, shoe_id: 1)
# yeezy2 = ShoeStore.create(quantity: 1, store_id: 3, shoe_id: 2)
# yeezy3 = ShoeStore.create(quantity: 1, store_id: 3, shoe_id: 3)
# yeezy4 = ShoeStore.create(quantity: 1, store_id: 3, shoe_id: 4)
# yeezy5 = ShoeStore.create(quantity: 1, store_id: 3, shoe_id: 5)
#
# nmd1 = ShoeStore.create(quantity: 1, store_id: 3, shoe_id: 6)
# nmd2 = ShoeStore.create(quantity: 1, store_id: 3, shoe_id: 7)
# nmd3 = ShoeStore.create(quantity: 1, store_id: 3, shoe_id: 8)
#
# jordan1 = ShoeStore.create(quantity: 15, store_id: 1, shoe_id: 9)
# jordan2 = ShoeStore.create(quantity: 13, store_id: 1, shoe_id: 10)
# jordan3 = ShoeStore.create(quantity: 20, store_id: 1, shoe_id: 11)
# jordan4 = ShoeStore.create(quantity: 11, store_id: 1, shoe_id: 12)
# jordan5 = ShoeStore.create(quantity: 30, store_id: 1, shoe_id: 13)
# jordan6 = ShoeStore.create(quantity: 10, store_id: 1, shoe_id: 14)
#
# jordan7 = ShoeStore.create(quantity: 9, store_id: 2, shoe_id: 9)
# jordan8 = ShoeStore.create(quantity: 14, store_id: 2, shoe_id: 10)
# jordan9 = ShoeStore.create(quantity: 19, store_id: 2, shoe_id: 11)
# jordan10 = ShoeStore.create(quantity: 9, store_id: 2, shoe_id: 12)
# jordan11 = ShoeStore.create(quantity: 20, store_id: 2, shoe_id: 13)
# jordan12 = ShoeStore.create(quantity: 17, store_id: 2, shoe_id: 14)
#
# jordan13 = ShoeStore.create(quantity: 19, store_id: 4, shoe_id: 9)
# jordan14 = ShoeStore.create(quantity: 17, store_id: 4, shoe_id: 10)
# jordan15 = ShoeStore.create(quantity: 34, store_id: 4, shoe_id: 11)
# jordan16 = ShoeStore.create(quantity: 13, store_id: 4, shoe_id: 12)
# jordan17 = ShoeStore.create(quantity: 23, store_id: 4, shoe_id: 13)
# jordan18 = ShoeStore.create(quantity: 10, store_id: 4, shoe_id: 14)
#
# jordan19 = ShoeStore.create(quantity: 15, store_id: 5, shoe_id: 9)
# jordan20 = ShoeStore.create(quantity: 23, store_id: 5, shoe_id: 10)
# jordan21 = ShoeStore.create(quantity: 20, store_id: 5, shoe_id: 11)
# jordan22 = ShoeStore.create(quantity: 31, store_id: 5, shoe_id: 12)
# jordan23 = ShoeStore.create(quantity: 40, store_id: 5, shoe_id: 13)
# jordan24 = ShoeStore.create(quantity: 10, store_id: 5, shoe_id: 14)
#
# foam1 = ShoeStore.create(quantity: 10, store_id: 5, shoe_id: 15)
# foam2 = ShoeStore.create(quantity: 9, store_id: 5, shoe_id: 16)
# foam3 = ShoeStore.create(quantity: 13, store_id: 5, shoe_id: 17)
# foam4 = ShoeStore.create(quantity: 12, store_id: 5, shoe_id: 18)
# foam5 = ShoeStore.create(quantity: 7, store_id: 5, shoe_id: 19)
# foam6 = ShoeStore.create(quantity: 11, store_id: 5, shoe_id: 20)
#
# foam7 = ShoeStore.create(quantity: 5, store_id: 1, shoe_id: 15)
# foam8 = ShoeStore.create(quantity: 13, store_id: 1, shoe_id: 16)
# foam9 = ShoeStore.create(quantity: 20, store_id: 1, shoe_id: 17)
# foam10 = ShoeStore.create(quantity: 15, store_id: 1, shoe_id: 18)
# foam11 = ShoeStore.create(quantity: 2, store_id: 1, shoe_id: 19)
# foam12 = ShoeStore.create(quantity: 4, store_id: 1, shoe_id: 20)
#
# chuck1 = ShoeStore.create(quantity: 30, store_id: 1, shoe_id: 21)
# chuck2 = ShoeStore.create(quantity: 30, store_id: 1, shoe_id: 22)
# chuck3 = ShoeStore.create(quantity: 30, store_id: 1, shoe_id: 23)
# chuck4 = ShoeStore.create(quantity: 30, store_id: 1, shoe_id: 24)
# chuck5 = ShoeStore.create(quantity: 30, store_id: 1, shoe_id: 25)
# chuck6 = ShoeStore.create(quantity: 30, store_id: 1, shoe_id: 26)
# chuck7 = ShoeStore.create(quantity: 30, store_id: 1, shoe_id: 27)
# chuck8 = ShoeStore.create(quantity: 30, store_id: 1, shoe_id: 28)
# chuck9 = ShoeStore.create(quantity: 30, store_id: 1, shoe_id: 29)
#
# chuck10 = ShoeStore.create(quantity: 20, store_id: 2, shoe_id: 21)
# chuck11 = ShoeStore.create(quantity: 20, store_id: 2, shoe_id: 22)
# chuck12 = ShoeStore.create(quantity: 20, store_id: 2, shoe_id: 23)
# chuck13 = ShoeStore.create(quantity: 20, store_id: 2, shoe_id: 24)
# chuck14 = ShoeStore.create(quantity: 20, store_id: 2, shoe_id: 25)
# chuck15 = ShoeStore.create(quantity: 20, store_id: 2, shoe_id: 26)
# chuck16 = ShoeStore.create(quantity: 20, store_id: 2, shoe_id: 27)
# chuck17 = ShoeStore.create(quantity: 20, store_id: 2, shoe_id: 28)
# chuck18 = ShoeStore.create(quantity: 20, store_id: 2, shoe_id: 29)
#
# chuck19 = ShoeStore.create(quantity: 35, store_id: 3, shoe_id: 21)
# chuck20 = ShoeStore.create(quantity: 35, store_id: 3, shoe_id: 22)
# chuck21 = ShoeStore.create(quantity: 35, store_id: 3, shoe_id: 23)
# chuck22 = ShoeStore.create(quantity: 35, store_id: 3, shoe_id: 24)
# chuck23 = ShoeStore.create(quantity: 35, store_id: 3, shoe_id: 25)
# chuck24 = ShoeStore.create(quantity: 35, store_id: 3, shoe_id: 26)
# chuck25 = ShoeStore.create(quantity: 35, store_id: 3, shoe_id: 27)
# chuck26 = ShoeStore.create(quantity: 35, store_id: 3, shoe_id: 28)
# chuck27 = ShoeStore.create(quantity: 35, store_id: 3, shoe_id: 29)
#
# chuck28 = ShoeStore.create(quantity: 10, store_id: 4, shoe_id: 21)
# chuck29 = ShoeStore.create(quantity: 10, store_id: 4, shoe_id: 22)
# chuck30 = ShoeStore.create(quantity: 10, store_id: 4, shoe_id: 23)
# chuck31 = ShoeStore.create(quantity: 10, store_id: 4, shoe_id: 24)
# chuck32 = ShoeStore.create(quantity: 10, store_id: 4, shoe_id: 25)
# chuck33 = ShoeStore.create(quantity: 10, store_id: 4, shoe_id: 26)
# chuck34 = ShoeStore.create(quantity: 10, store_id: 4, shoe_id: 27)
# chuck35 = ShoeStore.create(quantity: 10, store_id: 4, shoe_id: 28)
# chuck36 = ShoeStore.create(quantity: 10, store_id: 4, shoe_id: 29)
#
# chuck37 = ShoeStore.create(quantity: 30, store_id: 5, shoe_id: 21)
# chuck38 = ShoeStore.create(quantity: 30, store_id: 5, shoe_id: 22)
# chuck39 = ShoeStore.create(quantity: 30, store_id: 5, shoe_id: 23)
# chuck40 = ShoeStore.create(quantity: 30, store_id: 5, shoe_id: 24)
# chuck41 = ShoeStore.create(quantity: 30, store_id: 5, shoe_id: 25)
# chuck42 = ShoeStore.create(quantity: 30, store_id: 5, shoe_id: 26)
# chuck43 = ShoeStore.create(quantity: 30, store_id: 5, shoe_id: 27)
# chuck44 = ShoeStore.create(quantity: 30, store_id: 5, shoe_id: 28)
# chuck45 = ShoeStore.create(quantity: 30, store_id: 5, shoe_id: 29)
#
# chuck46 = ShoeStore.create(quantity: 23, store_id: 6, shoe_id: 21)
# chuck47 = ShoeStore.create(quantity: 23, store_id: 6, shoe_id: 22)
# chuck48 = ShoeStore.create(quantity: 23, store_id: 6, shoe_id: 23)
# chuck49 = ShoeStore.create(quantity: 23, store_id: 6, shoe_id: 24)
# chuck50 = ShoeStore.create(quantity: 23, store_id: 6, shoe_id: 25)
# chuck51 = ShoeStore.create(quantity: 23, store_id: 6, shoe_id: 26)
# chuck52 = ShoeStore.create(quantity: 23, store_id: 6, shoe_id: 27)
# chuck53 = ShoeStore.create(quantity: 23, store_id: 6, shoe_id: 28)
# chuck54 = ShoeStore.create(quantity: 23, store_id: 6, shoe_id: 29)
#
# curry1 = ShoeStore.create(quantity: 13, store_id: 1, shoe_id: 30)
# curry2 = ShoeStore.create(quantity: 13, store_id: 1, shoe_id: 31)
# curry3 = ShoeStore.create(quantity: 13, store_id: 1, shoe_id: 32)
# curry4 = ShoeStore.create(quantity: 13, store_id: 1, shoe_id: 33)
# curry5 = ShoeStore.create(quantity: 13, store_id: 1, shoe_id: 34)
# curry6 = ShoeStore.create(quantity: 13, store_id: 1, shoe_id: 35)
#
# curry7 = ShoeStore.create(quantity: 13, store_id: 5, shoe_id: 30)
# curry8 = ShoeStore.create(quantity: 13, store_id: 5, shoe_id: 31)
# curry9 = ShoeStore.create(quantity: 13, store_id: 5, shoe_id: 32)
# curry10 = ShoeStore.create(quantity: 13, store_id: 5, shoe_id: 33)
# curry11 = ShoeStore.create(quantity: 13, store_id: 5, shoe_id: 34)
# curry12 = ShoeStore.create(quantity: 13, store_id: 5, shoe_id: 35)
#
# oldskool1 = ShoeStore.create(quantity: 18, store_id: 1, shoe_id: 36)
# oldskool2 = ShoeStore.create(quantity: 12, store_id: 1, shoe_id: 37)
# oldskool3 = ShoeStore.create(quantity: 1, store_id: 1, shoe_id: 38)
# oldskool4 = ShoeStore.create(quantity: 17, store_id: 1, shoe_id: 39)
# oldskool5 = ShoeStore.create(quantity: 20, store_id: 1, shoe_id: 40)
# oldskool6 = ShoeStore.create(quantity: 21, store_id: 1, shoe_id: 41)
# oldskool7 = ShoeStore.create(quantity: 8, store_id: 1, shoe_id: 42)
#
# oldskool8 = ShoeStore.create(quantity: 13, store_id: 2, shoe_id: 36)
# oldskool9 = ShoeStore.create(quantity: 12, store_id: 2, shoe_id: 37)
# oldskool10 = ShoeStore.create(quantity: 13, store_id: 2, shoe_id: 38)
# oldskool11 = ShoeStore.create(quantity: 14, store_id: 2, shoe_id: 39)
# oldskool12 = ShoeStore.create(quantity: 34, store_id: 2, shoe_id: 40)
# oldskool13 = ShoeStore.create(quantity: 21, store_id: 2, shoe_id: 41)
# oldskool14 = ShoeStore.create(quantity: 8, store_id: 2, shoe_id: 42)
#
# oldskool15 = ShoeStore.create(quantity: 24, store_id: 4, shoe_id: 36)
# oldskool16 = ShoeStore.create(quantity: 23, store_id: 4, shoe_id: 37)
# oldskool17 = ShoeStore.create(quantity: 13, store_id: 4, shoe_id: 38)
# oldskool18 = ShoeStore.create(quantity: 17, store_id: 4, shoe_id: 39)
# oldskool19 = ShoeStore.create(quantity: 28, store_id: 4, shoe_id: 40)
# oldskool20 = ShoeStore.create(quantity: 21, store_id: 4, shoe_id: 41)
# oldskool21 = ShoeStore.create(quantity: 3, store_id: 4, shoe_id: 42)
#
# air_mag1 = ShoeStore.create(quantity: 1, store_id: 3, shoe_id: 43)
